repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    -   id: black
        args: [--safe, --quiet, --line-length=79]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910   # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [types-requests==2.25.0]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.2  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
