repos:
-   repo: https://gitlab.com/madh-van/avoid-confluence
    rev: 515ed224cc4691155d2e2868e0b0e2f0fc293e1b
    hooks:
    -  id: ac
       args:
         - --toc
         - --input-format=org
    types: [python]
